## 1.0 Setup File

1.1 Import packages

In [61]:
import pandas as pd 
import requests # for making HTTP requests
from pathlib import Path
from urllib.parse import urlparse # for parsing URLs
import time

1.2 Read in .csv file

In [62]:
df = pd.read_csv('../Data/data.csv')

df.head()

,_id,coll_name,coll_place,description,lat,long,object_name,object_number,os_gridref,priref,repro_ref,strat_type,strat_unit,taxonomy,url
0,6696,unknown,Unknown,Fossilised remains of half of Silurian brachio...,NaN,NaN,Brachiopod,G.00400.001,unknown,654725,G.00400.001b.jpg; G.00400.001a.jpg,"Chronostratigraphy, Lithostratigraphy",Silurian Period; Aymestry Limestone Member,Kirkidium knightii,https://data.nhm.ac.uk/media/ludlow:G.00400.00...
1,7620,"Tarrant, P.; Tarrant, M.",Meadowley Hill,Fossilised remains of headshield of the Devoni...,52.533872,-2.487920,Fish,G.09365.002,SO6793,659204,G.09365.002a.jpg; G.09365.002b.jpg,Chronostratigraphy,Devonian Period; Ditton Series,Cephalaspis sp.,https://data.nhm.ac.uk/media/ludlow:G.09365.00...
2,6658,unknown,Unknown,Fossilised remains of the Silurian heliotid ta...,NaN,NaN,CORAL,G.00122,unknown,655457,G.00122a.jpg; G.00122b.jpg; G.00122c.jpg,"Chronostratigraphy, Lithostratigraphy",Silurian Period; Wenlock Series; Much Wenlock ...,Plasmopora sp.,https://data.nhm.ac.uk/media/ludlow:G.00122a.j...
3,6673,unknown,Mocktree,Fossilised remains of phragmacone of the Silur...,52.378964,-2.853479,Cephalopod,G.00183,SO4276,52039,G.00183.jpg,Chronostratigraphy,Silurian Period; Ludlow Series,Orthoceras ibex,https://data.nhm.ac.uk/media/ludlow:G.00183.jpg
4,6669,unknown,Buildwas,Fossilised complete shell of the Silurian orth...,52.632565,-2.533343,Brachiopod,G.00172,SJ6404,52030,G.00172.jpg,"Chronostratigraphy, Lithostratigraphy",Silurian Period; Wenlock Series; Wenlock Shale...,Dalejina hybrida,https://data.nhm.ac.uk/media/ludlow:G.00172.jpg

## 2.0 Clean Data File

2.1 Rename and Drop Columns

In [63]:
# Drop Unnecessary Columns
df.drop(columns=['coll_name', 'os_gridref','priref','repro_ref','coll_place','lat','long','object_number'], inplace=True)

In [64]:
# rename columns
df.rename(columns={'_id': 'fossil_id','strat_unit': 'period'}, inplace=True)

In [65]:
df.head()

,fossil_id,description,object_name,strat_type,period,taxonomy,url
0,6696,Fossilised remains of half of Silurian brachio...,Brachiopod,"Chronostratigraphy, Lithostratigraphy",Silurian Period; Aymestry Limestone Member,Kirkidium knightii,https://data.nhm.ac.uk/media/ludlow:G.00400.00...
1,7620,Fossilised remains of headshield of the Devoni...,Fish,Chronostratigraphy,Devonian Period; Ditton Series,Cephalaspis sp.,https://data.nhm.ac.uk/media/ludlow:G.09365.00...
2,6658,Fossilised remains of the Silurian heliotid ta...,CORAL,"Chronostratigraphy, Lithostratigraphy",Silurian Period; Wenlock Series; Much Wenlock ...,Plasmopora sp.,https://data.nhm.ac.uk/media/ludlow:G.00122a.j...
3,6673,Fossilised remains of phragmacone of the Silur...,Cephalopod,Chronostratigraphy,Silurian Period; Ludlow Series,Orthoceras ibex,https://data.nhm.ac.uk/media/ludlow:G.00183.jpg
4,6669,Fossilised complete shell of the Silurian orth...,Brachiopod,"Chronostratigraphy, Lithostratigraphy",Silurian Period; Wenlock Series; Wenlock Shale...,Dalejina hybrida,https://data.nhm.ac.uk/media/ludlow:G.00172.jpg

In [66]:
df.shape

(2617, 7)

2.2 Drop columns without period or url

In [67]:
# remove NA's from the period column
df.dropna(subset=['period'], inplace=True)
df.shape

(2367, 7)

In [68]:
# remove NA's from the url column
df.dropna(subset=['url'], inplace=True)
df.shape

(2367, 7)

In [69]:
# remove "unknown" from the period column
df = df[df['period'] != 'Unknown']
df.shape

(2358, 7)

2.3 Clean Period Column to Isolate Periods

In [70]:
# get list of all unique periods
periods = df['period'].unique()
print(periods)

['Silurian Period; Aymestry Limestone Member'
 'Devonian Period; Ditton Series'
 'Silurian Period; Wenlock Series; Much Wenlock Limestone Formation'
 'Silurian Period; Ludlow Series'
 'Silurian Period; Wenlock Series; Wenlock Shale Formation'
 'Ordovician Period' 'Devonian Period' 'Ordovician Period; Caradoc Series'
 'Silurian Period; Upper Bringewood Formation'
 'Devonian Period; Caithness Flagstone Group'
 'Silurian Period; Whitcliffe Formation; Ludlow Series'
 'Silurian Period; Ludlow Series; Middle Elton Formation'
 'Devonian Period; Caithness Flagstone Group; Achanarras Limestone Member'
 'Ordovician Period; Llandeilian Stage'
 'Ordovician; Ludlow Series; Upper Bringewood Formation' 'Silurian Period'
 'Silurian Period; Whitcliffe Formation'
 'Silurian Period; Elton Formation'
 'Silurian Period; Ludlow Series; Bringewood Formation'
 'Silurian Period; Lower Bringewood Formation'
 'Silurian Period; Ludlow Series; Whitcliffe Formation' 'Pridoli Series'
 'Permian Period' 'Silurian Period; Pridoli Series; Ludlow Bone Bed'
 'Devonian; Pridoli Series'
 'Ordovician Period; Caradoc Series; Longvillian Stage'
 'Neogene Period; Pliocene Series' 'Neogene Period; Miocene series'
 'Quaternary Period; Pleistocene Series' 'Neogene Period'
 'Silurian; Much Wenlock Limestone Formation'
 'Devonian Period; Lochkovien stage' 'Silurian; Ludfordian Stage'
 'Silurian Period; Ludlow Series; Elton Formation'
 'Silurian Period; Pridoli Series' 'Silurian Period; Ludfordian Stage'
 'Jurassic Period' 'Carboniferous Period'
 'Silurian Period; Wenlock Series'
 'Devonian Period; Lower Ditton Series; Lochkovien stage'
 'Silurian Period; Middle Elton Formation'
 'Silurian Period; Lower Whitcliffe Formation; Ludlow Series' 'Miocene'
 'Silurian Period; Ludlow Series; Lower Whitcliffe Formation'
 'Silurian Period; Coalbrookdale Formation'
 'Silurian Period; Upper Leintwardine Formation'
 'Silurian Period; Pridoli Series; Traquairaspis symondsi zone'
 'Jurassic Period; Lower Lias' 'Cretaceous Period'
 'Silurian; Elton Formation' 'Triassic Period'
 'Silurian Period; Wenlock Series; Coalbrookdale Formation'
 'Silurian Period; Upper Bringewood Formation; Aymestry Limestone Member'
 'Silurian Period; Upper Bringewood Beds'
 'Silurian Period; Much Wenlock Limestone Formation'
 'Devonian Period; Eifelian Stage; Caithness Flagstone Group; Achanarras Limestone Member'
 'Carboniferous Period; Pensylvanian Subsystem'
 'Ordovician Period; Llanvirn Series; Mytton Flags Formation'
 'Carboniferous'
 'Ordovician Period; Llanvirn Series; Weston Flags Formation'
 'Silurian Period; Llandovery Series; Patrick Burn Formation'
 'Ordovician Period; Caradoc Series; Alternata Limestone'
 'Quaternary Period'
 'Silurian Period; Ludlow Series; Lower Leintwardine Formation'
 'Ordovician Period; Llandeilian Stage; Rorrington Shale Formation'
 "Ordovician Period; St. David's Series"
 'Silurian Period; Much Wenlock Limestone Formation; Much Wenlock Series'
 'Cambrian Period; Merioneth Series; Dolgellau beds'
 'Carboniferous Period; Pennsylvanian Subsystem'
 'Cretaceous Period; Upper Chalk Formation'
 'Silurian Period; Much Wenlock Series; Patrick Burn Formation'
 'Pennsylvanian Subsystem' 'Devonian Period; Dittonian'
 'Devonian Period; Tarrel Fish Bed' 'Jurassic Period; Callovian Stage'
 'Silurian Period; Wenlock Series; Patrick Burn Formation'
 'Jurassic Period; Kimmeridge Clay' 'Ordovician Period; Llanvirn Series'
 'Silurian Period; Llandovery Series'
 'Precambrian Eon; Ediacaran; Longmyndian; Wentnor Group; Bridges Formation'
 'Precambrian Eon; Ediacaran; Wentnor Group; Bridges Formation'
 'Silurian Period; Bringewood Formation'
 'Silurian Period; Ludlow Series; Ludfordian Stage' 'Palaeogene Period'
 'Ordovician Period; Caradoc Series; Chatwall Sandstone'
 'Silurian Period; Lower Leintwardine Formation'
 'Silurian; Ludlow Series; Whitcliffe Formation'
 'Precambrian Eon; Longmyndian Supergroup; Bayston-Oakwood Formation'
 'Silurian Period; Leintwardine Formation'
 'Triassic Period; Tarporley Siltstones'
 'Silurian Period; Ludlow Series; Higher Lower Leinwardine Beds'
 'Triassic Period; Mercia Mudstone Group; Tarporley Siltstone Formation'
 'Silurian Period; Ludlow Series; Lower Bringewood Formation'
 'Silurian Period; Pridoli Series; Red Downtonian Formation'
 'Silurian; Whitcliffe Formation'
 'Silurian Period; Ludlow Series; Upper Bringewood Formation'
 'Silurian; Llandovery Series' 'Silurian Period; Prodoli Series'
 'Silurian; Llandovery Series; Rubery Sandstone'
 'Silurian; Ludlow Series; Much Wenlock Limestone Formation'
 'Silurian Period; Rubery Sandstone' 'Silurian; Leintwardine Formation'
 'Triassic Period; Tarporley Siltstone Formation'
 'Silurian Period; Llandovery Series; Venusbank Formation'
 'Silurian Period; Pridoli Series; Rubery Shales'
 'Ordovician Period; Caradoc Series; Cheney Longville Flag Formation'
 'Ordovician Period; Tremadoc Series' 'Precambrian Eon'
 'Silurian Period; Old Red Sandstone'
 'Ordovician Period; Llanvirn Series; Hope Shale Formation'
 'Silurian Period; Bringewood Beds'
 'Triassic Period; Anisian Stage; Grinshill flagstone member'
 'Ordovician Period; Arenig Series; Hope Shale Formation'
 'Silurian Period; Downton Castle Sandstone Formation'
 'Silurian Period; Wenlock Shale Formation'
 'Ordovician Period; Llandeilian Stage; Meadowtown Formation'
 'Cretaceous Period; Upper Greensand Formation'
 'Carboniferous Period; Visean Stage'
 'Precambrian Eon; Stretton Group; Synalds Formation' 'Cenozoic Era'
 'Carboniferous Period; Mississippian Subsystem'
 'Ordovician Period; Caradoc Series; Cheney Longville Formation'
 'Quaternary Period; Boulder Clay'
 'Ordovician Period; Caradoc Series; Acton Scott Formation'
 'Silurian Period; Llandovery Series; Kenley Grit Member'
 'Tertiary Period' 'Neogene Period; Pliocene Epoch'
 'Eocene Epoch; Bracklesham Group'
 'Silurian Period; Much Wenlock Series; Much Wenlock Limestone Formation'
 'Eocene Epoch' 'Cambrian Period; Tremadoc Series'
 'Paleogene Period; Eocene Series'
 'Silurian Period; Ludlow Series; Aymestry Limestone Member'
 'Cambrian Period' 'Silurian; Upper Bringewood Formation'
 'Silurian; Ludlow Series; Bringewood Formation'
 'Ordovician Period; Caradoc Series; Longvillian Substage; Horderley Sandstone Formation'
 'Silurian Period; Middle Elton Formation; Ludlow Series'
 'Carboniferous Period; Coal Measures group'
 'Silurian Period; Llandovery Series; Pentamerus Sandstone Formation'
 'Ordovician Period; Caradoc Series; Longvillian Substage; K. bipartita zone'
 'Silurian Period; Ludlow Series; Bringewood Formation; Aymestry Limestone Member'
 'Silurian Period; Upper Bringewood Formation; Ludlow Series'
 'Silurian Period; Ludlow Series; Leintwardine Formation'
 'Ordovician Period; Caradoc Series; Soudleyan Substage'
 'Silurian Period; Pridoli Series; Downton Castle Sandstone Formation; Ludlow Bone Bed'
 'Ordovician Period; Caradoc Series; Onnian Substage; Onnia superba zone'
 'Silurian Period; Wenlock Limestone'
 'Triassic Period; Anisian Stage; Tarporley Siltstone Formation'
 'Cretaceous Period; Gault Formation'
 'Silurian Period; Lower Whitcliffe Formation'
 'Devonian Period; Hunsruck Slate'
 'Silurian Period; Llandovery Series; Rubery Sandstone Formation'
 'Cambrian Period; Comley Series; Wrekin Quartzite'
 'Silurian; Aymestry Limestone Member' 'Silurian Period; Ludlow'
 'Ordovician Period; Caradoc Series; Actonian Substage; Acton Scott Formation'
 'Silurian; Wenlock Series; Much Wenlock Limestone Formation'
 'Ordovician Period; Caradoc Series; Marshbrookian Stage; Upper Cheney Longville Flag Formation'
 'Silurian Period; Wenlock Series; Wenlock Limestone'
 'Devonian Period; Lower Lochkovian stage'
 'Silurian Period; Ludlow Bone Bed'
 'Ordovician Period; Caradoc Series; Longvillian Substage' 'Ordovician'
 'Silurian Period; Red Downtonian Formation'
 'Silurian Period; Much Wenlock Shale Formation; Much Wenlock Series'
 'Carboniferous Period; Coal Measure Series'
 'Silurian Period; Orthonota Mudstone Formation'
 'Silurian Period; Coalbrookdale Formation; Much Wenlock Series'
 'Carboniferous Period; Coal Measures'
 'Silurian Period; Much Wenlock Limestone Formation; Wenlock Series'
 'Silurian Period; Ludlow Series; Fuchsella Mudstone Formation'
 'Cambrian Period; Merioneth Series; Maentwrogian stage'
 'Devonian Period; Dittonian Series'
 'Silurian Period; Ludlow Series; Elton Beds' 'Pliocene Period'
 'Silurian Period; Elton Formation; Ludlow Series'
 'Cretaceous Period; Lautus Zone'
 'Carboniferous Period; Upper Carboniferous Series'
 'Ordovician Period; Llanvirn Series; Rorrington Shale Formation'
 'Devonian Period; Ditton Series; Hopton Wafers formation'
 'Silurian Period; Wenlock Series; Much Wenlock Limestone Formation.'
 'Ordovician Period; Caradoc Series; Chatwall Flags'
 'Silurian; Lower Ludlow Beds' 'Silurian'
 'Silurian Period; Ludlow Series; Fuchsella Mudstones'
 'Silurian; Ludlow Series; Fuchsella Mudstones'
 'Silurian Period; Lower Ludlow Beds'
 'Ordovician Period; Caradoc Series; Horderley Sandstone Formation'
 'Ordovician Period; Meadowtown Formation'
 'Silurian Period; Much Wenlock Series; Coalbrookdale Formation'
 'Silurian Period; Ludlow Series; Higher Lower Leintwardine Beds'
 'Precambrian Eon; Ediacaran Period; Wentnor Group; Bridges Formation'
 "Cambrian Period; St. David's Series"
 'Carboniferous Period; Westphalian Stage'
 'Precambrian Eon; Longmyndian Supergroup; Wentnor Group'
 'Devonian Period; Givetian Stage'
 'Silurian Period; Llandovery Series; Rubery Sandstone'
 'Silurian Period; Wenlock Series; Upper Elton Formation'
 'Ordovician Period; Llandeilian Stage; Caradoc Series'
 'Jurassic Period; boueti beds'
 'Precambrian Eon; Longmyndian; Wentnor Group; Bridges Formation'
 'Ordovician Period; Llanvirn Series; Betton Shale Formation'
 'Cretaceous Period; Chalk Formation'
 'Devonian Period; Cadbol Point Nodule Beds'
 'Devonian Period; Eifelian Stage; Caithness Flagstone Group'
 'Carboniferous Period; Shrimp Band; Lower Oil Shale; Calciferous Sandstone'
 'Precambrian Eon; Ediacaran; Longmyndian; Portway Formation'
 'Jurassic Period; Oxfordian Stage'
 'Silurian Period; Ludlow Series; Upper Elton Formation'
 'Devonian Period; Red Downtonian Formation'
 'Jurassic Period; Oxford Clay'
 'Carboniferous Period; Westphalian Stage; Highley Beds'
 'Silurian Period; Pridoli Series; Lochkovien stage'
 'Palaeogene Period; London Clay Formation'
 'Precambrian Eon; Ediacaran Period; Longmyndian Supergroup; Wentnor Group; Bridges Formation'
 'Silurian Period; Wenlock Series; Much Wenlock Limestone' 'Neogene'
 'Silurian Period; Ludlow Series; Bringewood Beds'
 'Precambrian Eon; Ediacaran Period; Longmyndian Supergroup; Wentnor Group; Bayston - Oakswood Formation'
 'Silurian Period; Pridoli Series; Downton Castle Sandstone Formation'
 'Siliurian Period; Pridoli Series'
 'Paleogene Period; Eocene Epoch; Beds of Haring'
 'Carboniferous Period; Pennsylvanian Subsystem; Mazon Creek Formation'
 'Devonian Period; Caithness Flagstone Series'
 'Silurian Period; Higher Lower Leintwardine Beds'
 'Silurian; Upper Leintwardine Formation'
 'Palaeogene Period; Eocene Series'
 'Jurassic Period; Upper Jurassic Series; Kimmeridgian Stage'
 'Cambrian Period; Comley Series'
 'Jurassic Period; Oxfordian Stage; Ampthill Clay Formation'
 'Ordovician Period; Stapeley Volcanic Member'
 'Silurian Period; Bringewood Formation; Ludlow Series'
 'Silurian; Ludlow Series; Lower Bringewood Formation'
 'Triassic Period; Rhaetian stage' 'Jurassic'
 'Silurian Period; Pridoli Series; Ledbury Formation' 'Archaeon Eon'
 'Permian Period; Bridgnorth Sandstone Formation'
 'Silurian Period; Llandovery Series; Purple Shale Formation'
 'Ordovician Period; Llanvirn Series; Hope Shale Formation; Stapeley Volcanic Member'
 'Cambrian Period; Lower Comley Sandstone'
 'Ordovician Period; Caradoc Series; Harnagian Substage'
 'Palaeogene Period; Eocene Series; Barton Group'
 'Precambrian Eon; Wentnor Group'
 'Ordovician Period; Arenig Series; Mytton Flags Formation'
 'Carboniferous Period; Cornbrook Sandstone Formation'
 'Silurian Period; Coalbrookdale Formation; Wenlock Series'
 'Silurian; Llandovery Series; Bog Quartzite'
 'Silurian Period; Downton Series' 'Pleistocene Epoch'
 'Precambrian Eon; Uriconian' 'Cretaceous Period; Weald Clay Formation'
 'Upper Carboniferous' 'Carboniferous Period; Coed-yr-Allt Formation'
 'Precambrian Eon; Longmyndian Supergroup'
 'Carboniferous Period; Chadian Stage; Oreton Limestone Formation'
 'Neogene Period; Miocene Epoch'
 'Triassic Period; Keuper Sandstone Formation'
 'Quaternary Period; Pleistocene Series; Devensian'
 'Ordovician Period; Caradoc Series; Hoar Edge Grit Formation'
 'Ordovician Period; Maquoketa Formation'
 'Silurian Period; Lower Old Red Sandstone'
 'Ordovician Period; Caradoc Series; Middletown Formation'
 'Permian Period; Keele Beds'
 'Ordovician Period; Llanvirn Series; Stapeley Volcanic Member'
 'Eocene Epoch; Barton Group'
 'Cambrian Period; Comley Series; Comley Sandstone Formation'
 'Carboniferous Period; Coal Measures group; Pennystone Band'
 'Neogene Period; Pliocene Series; San Joaquin Formation'
 'Silurian Period; Ludlow Series; Much Wenlock Limestone Formation'
 'Carboniferous Period; Pennystone Band'
 'Cretaceous Period; Tunbridge Wells Sand Formation'
 'Triassic Period; Anisian Stage; Tarporley Siltstones'
 'Ordovician Period; Tremadocian Stage; Shineton Shale Formation'
 'Precambrian Eon; Stretton Group'
 'Ordovician Period; Caradoc Series; Onnian Substage' 'Miocene period'
 'Ordovician Period; Caradoc Series; Actonian Substage; Onnia Grandis Zone'
 'Silurian Period; Pentamerus Sandstone Formation'
 'Ordovician Period; Tremadoc Series; Shineton Shale Formation'
 'Ordovician Period; Caradoc Series; Costonian Substage'
 'Jurassic Period; lower oolite'
 'Ordovician Period; Cheney Longville Flag Formation'
 'Ordovician Period; Caradoc Series; Aeronian Stage; Longvillian Substage'
 'Silurian Period; Mytton Flags Formation'
 'Silurian Period; Pridoli Series; Clun Forest Formation'
 'Precambrian Eon; Cardingmill Grit Formation'
 'Jurassic Period; Middle Lias Group' 'Precambrian Eon; Ediacaran Period'
 'Ordovician Period; Tremadocian Stage'
 'Precambrian Eon; Longmyndian Supergroup; Bayston Group'
 'Devonian Period; Lower Lochkovien'
 'Jurassic Period; Marlstone Rock Formation'
 'Devonian Period; Eifelian Stage'
 'Silurian Period; Wenlock Series; Homerian Stage; Much Wenlock Limestone Formation'
 'Silurian Period; Llandovery Series; Buttington Shales'
 'Paleogene Period; Eocene Epoch' 'Cretaceous Period; Valanginian stage'
 'Ordovician Period; Caradoc Series; Hoar Edge Grits'
 'Precambrian Eon; Ediacaran; Burway Formation'
 'Devonian Period; Strath Rory Group; Edderton Fish Beds'
 'Silurian Period; Rubery Sandstone Formation'
 'Cambrian Period; Merioneth Series; Festiniog beds'
 'Tertiary Period; Eocene Series'
 'Cretaceous Period; Upper Chalk Group; Flamborough Sponge Bed Formation'
 'Jurassic Period; Great Oolite Clay'
 'Jurassic; Lower Jurassic Series; Buckland 1 Beds'
 'Silurian Period; Lower Elton Formation'
 'Jurassic Period; Inferior Oolite Group'
 'Ordovician Period; Caradoc Series; Costonian Substage; Hoar Edge Grit Formation'
 'Palaeogene Period; Green River Formation' 'Neocomian Clay.'
 'Ordovician Period; Arenig Series; Stiperstones Quartzite Formation'
 'Jurassic Period; Kimmeridgian Stage'
 'Cretaceous Period; Campanian Stage'
 'Carboniferous Period; Coal Measures; Pennystone Band']

In [71]:
# drop everything after first semi-colon 
df['period'] = df['period'].str.split(';').str[0]

# remove leading and trailing whitespace
df['period'] = df['period'].str.strip()

# capitalizze using title case
df['period'] = df['period'].str.title()

# get list of all unique periods and number of fossils in each period
period_counts = df['period'].value_counts()
print(period_counts)

period
Silurian Period            982
Ordovician Period          337
Carboniferous Period       227
Devonian Period            224
Jurassic Period            121
Neogene Period             112
Precambrian Eon             74
Cretaceous Period           63
Silurian                    46
Triassic Period             41
Cambrian Period             28
Quaternary Period           22
Tertiary Period             15
Permian Period              14
Palaeogene Period           10
Paleogene Period             5
Cenozoic Era                 5
Eocene Epoch                 5
Pennsylvanian Subsystem      5
Ordovician                   2
Miocene                      2
Devonian                     2
Neogene                      2
Jurassic                     2
Pleistocene Epoch            2
Upper Carboniferous          2
Miocene Period               2
Pridoli Series               1
Carboniferous                1
Pliocene Period              1
Siliurian Period             1
Archaeon Eon                 1
Neocomian Clay.              1
Name: count, dtype: int64

In [72]:
# combine like periods
df['period'] = df['period'].replace({'Jurassic': 'Jurassic Period', 
                                    'Upper Carboniferous': 'Carboniferous Period',
                                    'Pennsylvanian Subsystem': 'Carboniferous Period',
                                    'Tertiary Period': 'Cenozoic Era',
                                    'Quaternary Period': 'Cenozoic Era',
                                    'Pleistocene Epoch': 'Cenozoic Era',
                                    'Pliocene Epoch': 'Cenozoic Era',
                                    'Silurian': 'Silurian Period',
                                    'Palaeogene Period': 'Cenozoic Era',
                                    'Neogene Period': 'Cenozoic Era',
                                    'Eocene Epoch': 'Cenozoic Era',
                                    'Paleogene Period': 'Cenozoic Era'})

# drop small periods
small_periods = period_counts[period_counts < 5].index
df = df[~df['period'].isin(small_periods)]

# get list of all unique periods and number of fossils in each period
period_counts = df['period'].value_counts()
print(period_counts)

period
Silurian Period         1028
Ordovician Period        337
Carboniferous Period     234
Devonian Period          224
Cenozoic Era             176
Jurassic Period          123
Precambrian Eon           74
Cretaceous Period         63
Triassic Period           41
Cambrian Period           28
Permian Period            14
Name: count, dtype: int64